### ISSUE TITLE
Where are images?

### ISSUE THREAD

**Issue by alundiak** [lonelyghost/jquery-rating#1]
Should it be sources from 
- here: http://www.fyneworks.com/jquery/star-rating/ ? or 
- here https://code.google.com/p/jquery-star-rating-plugin/source/checkout ? or 
- here http://jquery-star-rating-plugin.googlecode.com/svn/trunk/ ?

In css is reference to stars.png file, but on all resources mentioned there is star.gif.

**Comment by lonelyghost** [comment]
Sorry - I didn't end up using this, so this repository is not being maintained at all.

Should be the first link. If there are differences, they were things that we customized in our application.

**Comment by alundiak** [comment]
@lonelyghost is there any other *rating plugin u would suggest to use, which is maintained on regular basis?

**Comment by lonelyghost** [comment]
I don't know of one, sorry. We ended up writing our own Ember component.
